# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import server.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160513_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(default=server.main.models.Shortener.new_url, max_length=200),
        ),
    ]
