# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='homework',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
